// Imporing Part
import type { Metadata } from 'next';

// Exporting meta data of pages
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

// Exporting Root Layout as default which takes children as props
// and returns html template of pages
export default function RootLayout({children}:{children:React.ReactNode}) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}